language: python

python:
  - "3.5.1"

install:
  - pip install -r requirements.txt
  - pip install Django==2.1

script:
 - python manage.py makemigrations
 - python manage.py migrate
 - python manage.py test Show

sudo: false
